### ISSUE TITLE
Syntax error from CSS minify tool

### ISSUE THREAD

**Issue by mashirozx** [gavinmcfarland/flex-gap-polyfill#43]
![image](https://user-images.githubusercontent.com/16148054/127260083-35e627ae-e12c-4d18-a282-a4800a1a4a6a.png)

This is a flex item, I tried to remove the `var(--parent-has-fgp)`, and it just works fine. But I don't know why it generate this `var(--parent-has-fgp) ` at all...

**Comment by mashirozx** [comment]
Some info:

```js
module.exports = ({ env, options }) => ({
  ...options,
  plugins: [require('autoprefixer')(), require('flex-gap-polyfill')()],
})
```

"vue": "^3.1.4",
"sass": "^1.35.1",
"sass-loader": "^12.1.0",
"vite": "^2.4.2",

**Comment by limitlessloop** [comment]
Hi,

Are you still having an issue with this? Is it Chrome where the syntax issue is being reported? My suspicion is that Chrome is incorrectly reporting this.

**Comment by mashirozx** [comment]
Hi! I finally found it was actually a compatibility issue with [Vite](https://vitejs.dev) and [esbuild](https://esbuild.github.io/) ([Vite works depending on esbuil](https://vitejs.dev/config/#esbuild)). When [esbuild minifying CSS](https://vitejs.dev/config/#build-minify), it shows some of --fgp-* variables are invalid and ignoring them, so the polyfill not work after build.

**Comment by limitlessloop** [comment]
Hmm interesting. If you have a repo you're able to share I can investigate it and try to find a solution. Many thanks.

**Comment by mashirozx** [comment]
I've created a small demo: https://github.com/mashirozx/flex-polyfill-debug-demo

Some information: 
HTML and styles here: [App.vue](https://github.com/mashirozx/flex-polyfill-debug-demo/blob/master/src/App.vue)

Without polyfill:
![image](https://user-images.githubusercontent.com/16148054/127757592-00b4d988-d876-4a90-8299-0287ba95ee4b.png)

Polyfill on dev server (css not minified):
![image](https://user-images.githubusercontent.com/16148054/127757617-27a84a81-2578-464b-8116-f08ca08d3def.png)

Polyfill on build (./dist):
![image](https://user-images.githubusercontent.com/16148054/127757670-a260c16c-2207-411d-aed2-bc8dbcd636d4.png)

I unchecked the `gap` property because what we need is to polyfill it when browser not support it. Problem is here:
![image](https://user-images.githubusercontent.com/16148054/127757709-1a9f40a5-c60b-4bce-b741-323819237775.png)

And while `yarn build`, we can see this:
![image](https://user-images.githubusercontent.com/16148054/127757764-c380ceb1-cfb8-498b-a0d4-23a082179faf.png)

**Comment by limitlessloop** [comment]
Thank you, this is really useful. I'll spin this up and take a look.

With regards to the esbuild minifying the CSS I think this is a mistake being made by the minification tool. Although the property may look empty, there is actually a space as a value which is valid CSS. It uses this to toggle between values. We'd have to create a ticket for the esbuild minification to address this.

**Comment by mashirozx** [comment]
Well, I'm not 100% sure it is the ESbuild's problem (maybe another modules depended by Vite), there may still need more investigation.

And also I found some other strange problem. You can find it in picture 2 above.

![image](https://user-images.githubusercontent.com/16148054/127801472-4af86055-7e68-4531-9514-6db26484ca73.png)

This occurs on dev server, whose code is not minified, the width is incorrect, do you have any idea on this?

**Comment by limitlessloop** [comment]
Yes regarding the last problem. I had a little play around and it's because of the negative margin on the container and the width being applied is causing the width to be smaller than it is. The answer is to add the column gap to the width using calc but it will need a bit of extra work to make sure this works universally with the polyfill.

**Comment by limitlessloop** [comment]
Hi @mashirozx in your particular case you can try this snippet below:

```css
.flex-box {
    /* Only add to containers with explicit width */
    --fgp-width: var(--has-fgp) calc(170px + var(--fgp-gap-column));
    width: var(--fgp-width, 170px);
}
```

I'm working on a method to enable this with the polyfill.

**Comment by mashirozx** [comment]
But when I added this, the polyfills were gone 😢 
![image](https://user-images.githubusercontent.com/16148054/128636820-9dde2bc2-d0ad-4d82-b7b4-c37cc91a0c9c.png)

**Comment by limitlessloop** [comment]
Ahh. Sorry my bad. I forgot the plugin looks for properties beginning with `--fgp` to tell if the polyfill has been applied or not. Just change the prefix or you can remove it entirely, `--width` will suffice.

**Comment by limitlessloop** [comment]
I've released a fix for the width issue you were encountering. The problem should be resolved in version `4.1.0`.

Regarding the syntax error, I believe this is an error with the tool that minimises the CSS because it is removing empty custom properties which are valid CSS.

**Comment by limitlessloop** [comment]
Just did some lite research and I think I've found an option to disable hopefully removing empty properties `removeEmpty: true`. More information is on the [css-clean documentation.

**Comment by gavinmcfarland** [comment]
I'm closing this for now, as empty properties are needed for the polyfill to work. People can try the suggestion above to see if it resolves the issue.
