### ISSUE TITLE
Broken link for demo

### ISSUE THREAD

**Issue by yslpn** [gavinmcfarland/flex-gap-polyfill#61]
Hello. There is a demo link in the Readme.md file https://limitlessloop.github.io/flex-gap-polyfill/ but it won't open. Please fix it.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/14806611/179203593-90e1de44-f9fb-42ad-931d-248ca180ff18.png">

**Comment by gavinmcfarland** [comment]
Ah, thanks for flagging that. It's fixed now.
