### ISSUE TITLE
The example in the redeme doesn't work on IE 11

### ISSUE THREAD

**Issue by CasualMing** [gavinmcfarland/flex-gap-polyfill#70]
Chrome：
![image](https://user-images.githubusercontent.com/40878104/207521125-f51cb090-916e-439d-aee4-7581dcfb5213.png)

IE11：
![image](https://user-images.githubusercontent.com/40878104/207520645-272add3f-ff13-479c-a9f6-294db71a53b3.png)

**Comment by gavinmcfarland** [comment]
Hi @CasualMing. Thanks for your message. Unfortunately, this polyfill doesn't support IE11 because it relies on var support in CSS, which IE11 doesn't support. Apologies for that. This is documented later down in the readme.
