### ISSUE TITLE
plugin did not pass the `from` option to `postcss.parse`

### ISSUE THREAD

**Issue by kingyue737** [gavinmcfarland/flex-gap-polyfill#83]
I'm using this plugin with vite. The following warning is printed in console:

```
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.
```
postcss v8.4.23
flex-gap-polyfill v4.1.2

**Comment by gavinmcfarland** [comment]
Thanks for sharing this. This plugin does not use the method `postcss.parse` so I'm not sure what's causing this warning but I will investigate.

Is it preventing you from doing anything?

**Comment by wxin627** [comment]
hi, I met the same problem using Vite. This warning will stuck the build process, so the plugin will not work.

**Comment by kingyue737** [comment]
Thanks for investigating this. But you should mark #89 a duplicate of this issue instead.
