### ISSUE TITLE
Alternative to flex-gap-polyfill with TWBS 5

### ISSUE THREAD

**Issue by frugan-dev** [gavinmcfarland/flex-gap-polyfill#87]
Hi there,

I created this gist https://gist.github.com/frugan-it/19f94872e4b6005775d91350e87002bf and would love to hear some feedback from you..

Thanks!

**Comment by gavinmcfarland** [comment]
I just going to close this as an issue, but people can still find it if they want to look for alternatives. Thanks again!

**Comment by echoix** [comment]
Link is dead. Seems the user changed username. Link is https://gist.github.com/frugan-dev/19f94872e4b6005775d91350e87002bf
