### ISSUE TITLE
Throw error when using base64 format image in css

### ISSUE THREAD

**Issue by LeonDWong** [gavinmcfarland/flex-gap-polyfill#88]
Hello, i am using this plugin in my project which is based on nextjs and tailwind. But it throws error when compiling. It seems that the plugin is not compatible with base64. Could anyone help, thx.
<img width="1126" alt="image" src="https://github.com/gavinmcfarland/flex-gap-polyfill/assets/17465046/3af7af55-d2fc-4d1e-a3d2-a823163f4ed4">

package version: `"flex-gap-polyfill": "^4.2.0",`

**Comment by gavinmcfarland** [comment]
Hi @LeonDWong, can you share the CSS rule with the data image in it, and I will investigate?

Many thanks.

**Comment by zzzzzzdk** [comment]
Is this issue resolved?

**Comment by gavinmcfarland** [comment]
Hi @zzzzzzdk, I just need an example of the CSS snippet that's causing this issue and I can investigate it. Can you share one?

**Comment by gavinmcfarland** [comment]
I think I've been able to fix this in the latest release `4.2.1`. If not, let me know and if you could provide an example that would be great. Thank you.

**Comment by zzzzzzdk** [comment]
![企业微信截图_17224733781648](https://github.com/user-attachments/assets/eb8e1b90-bf23-469f-b060-7536db09ad0c)

**Comment by gavinmcfarland** [comment]
Is this using version `4.2.1`? I need to know what snippet of CSS causes this, otherwise I can't debug it.
